In [28]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [29]:
df = pd.read_csv("../Dataset/StudentPerformanceFactors_Cleaned.csv")
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

ENCODE CATEGORICAL FEATURES

In [30]:
label_encoder = LabelEncoder()
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    df[column] = label_encoder.fit_transform(df[column])

df.head()

C:\Users\sumit\AppData\Local\Temp\ipykernel_6116\3663785741.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,1,0,0,7,73,1,1,0,1,2,1,2,3,0,1,2,1,67
1,19,64,1,2,0,8,59,1,1,2,2,2,1,0,4,0,0,1,0,61
2,24,98,2,2,1,7,91,2,1,2,2,2,1,1,4,0,2,2,1,74
3,29,89,1,2,1,8,98,2,1,1,2,2,1,0,4,0,1,1,1,71
4,19,92,2,2,1,6,65,2,1,3,2,0,1,1,4,0,0,2,0,70

SELECT FEATURES AND TARGET VARIABLES

In [31]:
X = df.drop("Exam_Score", axis=1)
y = df["Exam_Score"]

SPLIT THE DATASET

In [32]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

FEATURE SCALING

In [33]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("Feature Scaling Completed Successfully.")

Feature Scaling Completed Successfully.

TRAIN THE LINEAR REGRESSION MODEL

In [34]:
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
linear_predictions = linear_model.predict(X_test)
print("Linear Regression Model Trained Successfully.")

Linear Regression Model Trained Successfully.

TRAIN THE RANDOM FOREST REGRESSOR

In [35]:
rf_model = RandomForestRegressor(n_estimators = 100, random_state = 42)
rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)
print("Random Forest Regressor Trained Successfully.")

Random Forest Regressor Trained Successfully.

EVALUATE BOTH MODELS

In [37]:
# Linear Regression Evaluation
linear_mae = mean_absolute_error(y_test, linear_predictions)
linear_rmse = np.sqrt(mean_squared_error(y_test, linear_predictions))
linear_r2 = r2_score(y_test, linear_predictions)

print("Linear Regression Performance")
print(f"Mean Absolute Error (MAE): {linear_mae:.2f}")
print(f"Root Mean Squared Error (RMSE): {linear_rmse:.2f}")
print(f"R² Score: {linear_r2:.4f}({linear_r2*100:.1f}% Variance)")

# Random Forest Evaluation
rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_predictions))
rf_r2 = r2_score(y_test, rf_predictions)

print("\nRandom Forest Regressor")
print(f"Mean Absolute Error (MAE): {rf_mae:.2f}")
print(f"Root Mean Squared Error (RMSE): {rf_rmse:.2f}")
print(f"R² Score: {rf_r2:.4f}({rf_r2*100:.1f}% Variance)")

Linear Regression Performance
Mean Absolute Error (MAE): 1.02
Root Mean Squared Error (RMSE): 2.10
R² Score: 0.6888(68.9% Variance)

Random Forest Regressor
Mean Absolute Error (MAE): 1.13
Root Mean Squared Error (RMSE): 2.20
R² Score: 0.6577(65.8% Variance)

COMPARE MODEL PERFORMANCE

In [38]:
comparison = pd.DataFrame({"Model": ["Linear Regression", "Random Forest Regressor"],
                            "MAE": [linear_mae, rf_mae],
                            "RMSE": [linear_rmse, rf_rmse],
                            "R² Score": [linear_r2, rf_r2]})

comparison

                     Model       MAE      RMSE  R² Score
0        Linear Regression  1.015549  2.097445  0.688769
1  Random Forest Regressor  1.125166  2.199577  0.657721

RESULT

In [ ]:
models = ["Linear Regression", "Random Forest Regressor"]
mae = [linear_mae, rf_mae]
rmse = [linear_rmse, rf_rmse]
r2 = [linear_r2, rf_r2]

print("----Model Comparison----")
print("-" * 50)

for i in range(len(models)):
    print(f"Model     : {models[i]}")
    print(f"MAE       : {mae[i]:.2f}")
    print(f"RMSE      : {rmse[i]:.2f}")
    k
    print(f"R² Score  : {r2[i]:.4f}({r2[i]*100:.1f}% variance)")

print("-" * 50)

----Model Comparison----
--------------------------------------------------
Model     : Linear Regression
MAE       : 1.02
RMSE      : 2.10
R² Score  : 0.6888(68.9% variance)
Model     : Random Forest Regressor
MAE       : 1.13
RMSE      : 2.20
R² Score  : 0.6577(65.8% variance)
--------------------------------------------------